language: c
dist: trusty
services:
  - docker

cache:
  directories:
    - $HOME/docker

env:
  global:
    # DOCKERPASS
    - secure: "Vlh5o7wH3AVM234pGD2QaFkXm267cIXPnowAsn+j5HB7B0P1r88EuSTr83ZsaS/5K4r/7w11VIt0qmg2d9lhCL00+QKnawimu0MrXcevesjFYetyrfxv0G+ofEn/R1KhEhqarCBk20ng1cEcPCx7p7Dg2R9oHAGHnooapLWdEb5xCE7djgOoulsOC4SNX4s5Pt9biEFwNS9TRzTjfpxR0kAcd6EYrdxIRJ6d2pwzdHWU6LYiEybLpkwRZysgcSSJeFiziIoYUglUPDXg+xAZA/vBSZQqmnjCa7VgcBU3znewgF7Nkz7vCaoHCZF60C7Ri2nkzRLkUgz0UjrxAKfDznqwFtMzy1dJ2xYqM+Pj1xXWUkf3hiT0AZfEMqx+9Tv4LEXwJuP519i0ZVcd4JrD7YkSntO9LQN9Xi5Z09dZlfAsKxEfP0o8gy4dnXTzIQczaMK/HHp1VEtErVEoIHydmio1Jwhf5/NQawsoP4MFP84Lb4G6SKPWkdQC+CYLg4nyo58dMUC5943z2vUzI/Fe37HLmFLkTUUsOcYpFkS5be//d2kqM2av+8gXOkVNpgX4H1rBsNGdc3Z/vv3neogzO3y1eDr/aDcKwlXkGgMcw9q+MIJ01h9rGN45d/723xC07F0lFKoPDtPenUCoWAzXXxuJjZdqWvxB7jrEQlzIUyg="


jobs:
  include:
    - stage: "Build pypy/manylinux images"

      script:
        - TRAVIS_COMMIT=$TRAVIS_COMMIT ./build.sh

      deploy:
        provider: script
        script: docker/deploy.sh
        on:
          branch: master
          repo: pypy/manylinux
